rolmodl: rolmodl::ren::driver Namespace Reference
rolmodl::ren::driver Namespace Reference
Renderer driver information functions.
Functions
unsigned int count ()
Query the amount of available rendering drivers.
Info info (const unsigned int i)
Query the driver info for the ith rendering driver.
Detailed Description
Renderer driver information functions.
Function Documentation
count()
unsigned int rolmodl::ren::driver::count ()
Query the amount of available rendering drivers.
Exceptions
rolmodl::sdlexception SDL reported an error code.
See also
https://wiki.libsdl.org/SDL_GetNumRenderDrivers
Definition at line 15 of file Ren.cpp.
References rolmodl::detail::throwOnErr().
Referenced by info().
info()
Info rolmodl::ren::driver::info (const unsigned int i)
Query the driver info for the ith rendering driver.
Exceptions
std::out_of_range Driver index is out of range.
See also
https://wiki.libsdl.org/SDL_GetRenderDriverInfo
Definition at line 21 of file Ren.cpp.
References count(), rolmodl::ren::Info::name, rolmodl::detail::throwOnErr(), and rolmodl::ren::Flags::unsafeFromRaw().